/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealersDealerIdRouteImport } from './routes/dealers.$dealerId'
import { Route as ApiCoachChatRouteImport } from './routes/api/coach-chat'

const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersDealerIdRoute = DealersDealerIdRouteImport.update({
  id: '/dealers/$dealerId',
  path: '/dealers/$dealerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachChatRoute = ApiCoachChatRouteImport.update({
  id: '/api/coach-chat',
  path: '/api/coach-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data' | '/api/coach-chat' | '/dealers/$dealerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data' | '/api/coach-chat' | '/dealers/$dealerId'
  id: '__root__' | '/' | '/data' | '/api/coach-chat' | '/dealers/$dealerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  ApiCoachChatRoute: typeof ApiCoachChatRoute
  DealersDealerIdRoute: typeof DealersDealerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers/$dealerId': {
      id: '/dealers/$dealerId'
      path: '/dealers/$dealerId'
      fullPath: '/dealers/$dealerId'
      preLoaderRoute: typeof DealersDealerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach-chat': {
      id: '/api/coach-chat'
      path: '/api/coach-chat'
      fullPath: '/api/coach-chat'
      preLoaderRoute: typeof ApiCoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  ApiCoachChatRoute: ApiCoachChatRoute,
  DealersDealerIdRoute: DealersDealerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
